### ISSUE TITLE
Is this project abandoned ?

### ISSUE THREAD

**Issue by Swizz** [pa7/nude.js#19]
Hi,

NudeJs seem to be awesome in lot of contexts,
I am working on a Cordova app for picture sharing and I am truly interested about your project.

I saw many of forks (like @forlooper or @goddamnbugs jobs) but I do not know the most advanced.

I tried your solution but results are really not reliable for grayscale pictures, non-white people or sandy colored subject.

I think to use neural networks or learning machines to do the job, what is your position about that ?

Kind regards,

**Comment by niksmac** [comment]
IMHO `neural networks` is a big player for this small project. Cant we do some more image processing to achieve this?

**Comment by Swizz540** [comment]
Yes, I know.
But they are many and many case of nudity.
And I think is really difficult to match all of them with pixels colors analysis.

Any idea ?

**Comment by niksmac** [comment]
@Swizz540 yeah, makes sense. I am interested in working this. Lets think through and start. Share some thoughts to get started.

**Comment by Swizz540** [comment]
Well.
I have no knowledge in neural networks. Only about the basics.

I carry many ideas, but no practise which could help us.

**Comment by vikasTmz** [comment]
From the [Original Paper](https://be82ac79-a-aff4c786-s-sites.googlegroups.com/a/dcs.upd.edu.ph/csp-proceedings/Home/pcsc-2005/AI4.pdf?attachauth=ANoY7cr2c7i2FNEzKw-rszbtOl_Jfx0hbn19GTf-55x2ivtE6myYQYnKD8W1xv_zPLa90fzCHw3RNMETUaFPRaazAcs5XMfnVVGDUwqWWx885oekJp4us7zwyBZSiezZt9pKUXo7nTbR9cOzxBUnaO0rnPMQG1XpUhktd8AJv5l97mV4C8nuERwHfXVy1BpKZvPCOsYnJydGOvI8LmSZLuVtdAH2tciyAc_a_rnCL3sAC19zMySS4DE%3D&attredirects=0):

> Jones & Rehg (1998) constructed skin and non-skin models from a dataset of nearly one billion labeled pixels. A neural network was then trained on 5453 adult images and 5226 non-adult images.    The procedure resulted in **93%** correct detections with **8%** false-positives. Lin, Chen, & Fuh (2003) 
contends that the training process for neural networks is very slow and difficult because pornography  classification is a matter of opinion

But this is an old paper and a lot of better and faster ANNs have been developed recently.

You can have a look at this [Cloth Parser](http://vision.is.tohoku.ac.jp/clothing_parsing/) which also segments out skin from the image. This parser was primarily trained on full body images, but as far as I have tested, it is skin-color invariant.

**Comment by GarkGarcia** [comment]
Does anyone have any update on that? [Microsoft Azure's Computer Vison](https://azure.microsoft.com/en-us/services/cognitive-services/computer-vision/) seems like the better alternative for now...

**Comment by pa7** [comment]
jep, anyone who's planning to solve nudity detection: there's plenty of new research that has been done in this field, nude.js was implemented based on an old paper and was more of a proof of concept to see how far we can push browsers at that time
